# Vellum deterministic engine — state rebuild / state check (spec 5.2).
# Original code (base design credited in ATTRIBUTION.md).
"""Regenerates state/_tracking-state.json and the 7-section state-card.md,
and checks the transactional invariants gate 1 relies on.

pending_capture semantics: true while any chapter has status exactly
`accepted` — i.e., the chapter transaction (LLM capture half via @kb-lead,
demolition decision, close to `final`) has not been completed for that
chapter. `state rebuild` derives it from sources on every run; `state check`
refuses a new-chapter start while it is set."""
import json
import os
import re
import sys
from datetime import datetime, timezone

from . import util
from .util import (EXIT_OK, EXIT_ERROR, EXIT_FINDINGS, SCHEMA_VERSION,
                   STATE_CARD_MAX_BYTES, atomic_write, die)

TRACKING_FILE = "state/_tracking-state.json"
CARD_FILE = "state/state-card.md"


# ---------------------------------------------------------------------------
# Source gathering
# ---------------------------------------------------------------------------

def _gather(root):
    chapters = util.list_chapters(root)
    characters = util.load_entity_dir(root, "characters")
    promises = util.load_entity_dir(root, "promises")
    questions = util.load_entity_dir(root, "questions")
    knowledge = util.load_entity_dir(root, "knowledge")
    props = util.load_entity_dir(root, "props")
    return chapters, characters, promises, questions, knowledge, props


def _clock_rows(root):
    """Parse kb/clock.md thread rows (| thread | started | position | reading | last |)."""
    path = util.project_file(root, "kb", "clock.md")
    rows = []
    if not os.path.exists(path):
        return rows
    for line in util.read_file(path).split("\n"):
        s = line.strip()
        if not s.startswith("|") or s.startswith("|--") or s.startswith("| thread"):
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if len(cells) >= 5:
            rows.append({"thread": cells[0], "started": cells[1],
                         "position": cells[2], "reading": cells[3],
                         "last_chapter": cells[4]})
    return rows


def _voice_debt(root):
    p = util.project_file(root, "work", "voice-debt.json")
    open_items = 0
    if os.path.exists(p):
        try:
            with open(p, "r", encoding="utf-8-sig") as f:
                doc = json.load(f)
            open_items = sum(1 for it in doc.get("items", [])
                             if it.get("status") == "open")
        except Exception:
            open_items = 0
    return open_items


def _exemptions_digest(root):
    doc = util.load_exemptions(root)
    active, stale = [], 0
    for e in doc.get("exemptions", []):
        if e.get("status") == "active":
            active.append(e)
        elif e.get("status") == "stale":
            stale += 1
    return active, stale


# ---------------------------------------------------------------------------
# State card (7 fixed sections, spec 7.4)
# ---------------------------------------------------------------------------

def _chapter_line(c):
    fm = c["fm"]
    return "- ch %s — %s (status: %s, %d words, POV %s)" % (
        fm.get("number", c["num"]), fm.get("title", c["name"]),
        fm.get("status", "unknown"), c["words"], fm.get("pov", "unset"))


def _promise_line(p):
    fm = p["fm"]
    parts = ["- %s — %s" % (fm.get("id"), fm.get("status", "?"))]
    if fm.get("planted-in"):
        parts.append("planted %s" % fm["planted-in"])
    if fm.get("target-by"):
        parts.append("target-by %s" % fm["target-by"])
    return " | ".join(parts)


def _build_card(root, chapters, characters, promises, questions, knowledge,
                props, pending):
    story = util.load_story(root)
    current = chapters[-1] if chapters else None
    cfg = util.load_config(root)

    L = []
    L.append("# State Card")
    L.append("")
    L.append("Generated by `vellum state rebuild` on %s. Machine-authoritative: "
             "never hand-edit (hash-verified). Sources: kb/, manuscript frontmatter, "
             "ledgers." % datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"))
    L.append("")

    # 1. Story position
    L.append("## Story position")
    L.append("")
    if current:
        fm = current["fm"]
        L.append("Current chapter: %s — \"%s\" (status: %s, %d words, target %s)."
                 % (current["file"], fm.get("title", "?"),
                    fm.get("status", "unknown"), current["words"],
                    fm.get("word-target", cfg.get("default_word_target"))))
        L.append("POV: %s. Cast in scene: %s."
                 % (fm.get("pov", "unset"),
                    ", ".join(_as_list(fm.get("characters"))) or "none recorded"))
    else:
        L.append("No chapters on disk yet.")
    pending_thr = [r for r in _clock_rows(root)]
    if pending_thr:
        r = pending_thr[-1]
        L.append("Clock: thread %s — %s (%s) as of %s."
                 % (r["thread"], r["position"], r["reading"], r["last_chapter"]))
    L.append("")

    # 2. Open promises & questions (top N by age)
    L.append("## Open promises & questions")
    L.append("")
    open_promises = [p for p in promises
                     if p["fm"].get("status") in
                     ("planned", "planted", "reinforced")]
    open_promises.sort(key=lambda p: util.chapter_num_val(p["fm"].get("planted-in")) or 0)
    for p in open_promises[:5]:
        L.append(_promise_line(p))
    open_questions = [q for q in questions
                      if q["fm"].get("status") in ("open", "dormant")]
    open_questions.sort(key=lambda q: util.chapter_num_val(q["fm"].get("raised-in")) or 0)
    for q in open_questions[:5]:
        L.append("- %s — %s (raised %s)" % (q["fm"].get("id"),
                                            q["fm"].get("status", "?"),
                                            q["fm"].get("raised-in") or "?"))
    if not open_promises and not open_questions:
        L.append("(none open)")
    L.append("")

    # 3. Active cast state
    L.append("## Active cast state")
    L.append("")
    byid = {}
    for c in chapters:
        for cid in _as_list(c["fm"].get("characters")):
            byid.setdefault(cid, c["num"])
    live = [e for e in characters if e["fm"].get("status") != "deceased"]
    if not live:
        L.append("(no character entities recorded)")
    for e in live:
        fm = e["fm"]
        eid = fm.get("id", e["name"][:-3])
        L.append("- %s (%s) — status: %s; last in scene ch %s%s"
                 % (eid, fm.get("name", "?"), fm.get("status", "?"),
                    byid.get(eid, "?"),
                    "; POV-eligible" if fm.get("pov-eligible") else ""))
    L.append("")

    # 4. Knowledge boundaries
    L.append("## Knowledge boundaries")
    L.append("")
    found = False
    for k in knowledge:
        fm = k["fm"]
        holders = fm.get("holders") or []
        if not isinstance(holders, list):
            continue
        for h in holders:
            if isinstance(h, dict) and h.get("certainty") in ("half-glimpse", "audience-only"):
                L.append("- %s: %s holds (%s) as of %s — %s"
                         % (fm.get("id"), h.get("character"),
                            h.get("certainty"), h.get("learned-in"),
                            fm.get("title", "")))
                found = True
    if not found:
        L.append("(no restricted-certainty knowledge recorded)")
    L.append("")

    # 5. Props & clock
    L.append("## Props & clock")
    L.append("")
    for p in props:
        fm = p["fm"]
        cust = fm.get("custody") or {}
        if isinstance(cust, dict):
            L.append("- %s — owner: %s, location: %s, status: %s"
                     % (fm.get("id"), cust.get("owner") or "none",
                        cust.get("location") or "?", cust.get("status", "?")))
    for r in _clock_rows(root):
        L.append("- thread %s — %s (%s), last chapter %s"
                 % (r["thread"], r["position"], r["reading"], r["last_chapter"]))
    if not props and not _clock_rows(root):
        L.append("(no props or clock threads recorded)")
    L.append("")

    # 6. Next beats with word quotas
    L.append("## Next beats with word quotas")
    L.append("")
    outlines = util.outline_files(root)
    nxt = None
    for num in sorted(outlines):
        o = outlines[num]
        if (o["fm"].get("approved") is True
                and not any(c["num"] == num for c in chapters)):
            nxt = o
            break
    if nxt:
        L.append("Next chapter: %s (approved outline, not yet drafted)."
                 % nxt["file"])
        for line in nxt["body"].split("\n"):
            s = line.strip()
            if s and not s.startswith("#"):
                L.append("- %s" % s)
    else:
        L.append("(no approved outline awaiting a draft)")
    L.append("")

    # 7. Flags
    L.append("## Flags")
    L.append("")
    active, stale = _exemptions_digest(root)
    L.append("- Exemptions: %d active, %d stale (re-armed)."
             % (len(active), stale))
    debt = _voice_debt(root)
    L.append("- Voice debt: %d open tier-1 item(s) in work/voice-debt.json."
             % debt)
    if pending:
        L.append("- WARNING: pending_capture is true — a chapter sits at "
                 "status: accepted; complete the capture close-out before the "
                 "next chapter.")
    L.append("")
    # Optional series layer: importing it is fail-open so deleting the
    # v0.2.0 modules leaves the v0.1.1 state output byte-identical.
    try:
        from . import series_bible
        series_section = series_bible.state_card_section(root)
    except Exception:
        series_section = None
    if series_section:
        # The series card must never push the whole card over the 12KB hard
        # cap: a linked book whose own sections already fill the card would
        # otherwise freeze (card_over_cap) purely from series-driven bloat,
        # with remediation advice ("cut prose in kb/") that cannot fix it.
        # Give the injected section the remaining budget, capped at 4KB.
        # The budget must also hold the truncation marker series_bible
        # appends when the section overflows: a series section larger than
        # the marker is skipped entirely, because emitting a truncated
        # section would push the whole card over the hard cap and freeze
        # the rebuild into card_over_cap with unfixable remediation advice.
        base = "\n".join(L) + "\n"
        budget = (STATE_CARD_MAX_BYTES
                  - len(base.encode("utf-8"))
                  - len("\n".encode("utf-8")))
        max_series = min(4 * 1024, max(budget, 0))
        if max_series > 0:
            series_section = series_bible.state_card_capped_with_budget(
                series_section, max_series)
            if series_section:
                L.append(series_section)
    return "\n".join(L)


def _as_list(v):
    if v is None:
        return []
    if isinstance(v, list):
        return [x for x in v if isinstance(x, str)]
    return [str(v)]


# ---------------------------------------------------------------------------
# rebuild
# ---------------------------------------------------------------------------

def _tracking_doc(root, chapters, pending):
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "pending_capture": pending,
        "current_chapter": (chapters[-1]["file"] if chapters else None),
        "voice_debt_open": _voice_debt(root),
        "chapters": [
            {
                "file": c["file"],
                "number": c["fm"].get("number", c["num"]),
                "status": c["fm"].get("status", "unknown"),
                "pov": c["fm"].get("pov"),
                "characters": _as_list(c["fm"].get("characters")),
                "mentions": _as_list(c["fm"].get("mentions")),
                "promises_advanced": _as_list(c["fm"].get("promises-advanced")),
                "word_target": c["fm"].get("word-target"),
                "word_count": c["fm"].get("word-count"),
            }
            for c in chapters
        ],
        "counts": {
            "chapters": len(chapters),
            "characters": 0,  # filled by callers with entity lists
            "promises": 0,
            "questions": 0,
            "knowledge": 0,
            "props": 0,
        },
    }


def rebuild(root):
    (chapters, characters, promises, questions,
     knowledge, props) = _gather(root)
    pending = any(c["fm"].get("status") == "accepted" for c in chapters)

    tracking = _tracking_doc(root, chapters, pending)
    tracking["counts"] = {
        "chapters": len(chapters),
        "characters": len(characters),
        "promises": len(promises),
        "questions": len(questions),
        "knowledge": len(knowledge),
        "props": len(props),
    }

    card = _build_card(root, chapters, characters, promises, questions,
                       knowledge, props, pending)

    release = util.lock_state(root)
    try:
        _rebuild_unlocked(root, tracking, card)
    finally:
        release()

    if tracking.get("card_over_cap"):
        sys.stdout.write(
            "state rebuilt: %d chapters, pending_capture=%s — WARNING: state "
            "card is over the %d-byte hard cap; the card on disk is frozen at "
            "its last good content (flagged in _tracking-state.json). Cut "
            "prose in the ledger sources (kb/) and rebuild.\n"
            % (len(chapters), "true" if pending else "false",
               STATE_CARD_MAX_BYTES))
    else:
        sys.stdout.write("state rebuilt: %d chapters, pending_capture=%s.\n"
                         % (len(chapters), "true" if pending else "false"))
    return EXIT_OK


_CARD_OVER_CAP_MARKER = "card rebuild refused: over cap"


def _card_with_cap(root, card):
    """Card content honoring the 12KB hard cap (spec 7.4).

    Under the cap: return (card, None). Over the cap: the rebuild cannot
    honestly regenerate the card, so the previous engine-written card is
    kept frozen (content unchanged) with a dated warning appended to its
    Flags section (the last section), and the date is returned so the
    caller can flag _tracking-state.json — the resume artifact then says
    so instead of silently serving stale content."""
    if len(card.encode("utf-8")) <= STATE_CARD_MAX_BYTES:
        return card, None
    when = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    card_path = util.project_file(root, *CARD_FILE.split("/"))
    if not os.path.exists(card_path):
        frozen = ("# State Card\n\n"
                  "## Flags\n\n"
                  "- WARNING (%s): %s (%d bytes > %d hard cap); no previous "
                  "card exists — cut prose in the ledger sources (kb/) and "
                  "run `vellum state rebuild`.\n"
                  % (when, _CARD_OVER_CAP_MARKER,
                     len(card.encode("utf-8")), STATE_CARD_MAX_BYTES))
        return frozen, when
    with open(card_path, "r", encoding="utf-8", errors="replace") as f:
        prev = f.read()
    # Strip any previous overflow warning so repeated rebuilds do not
    # accumulate warning lines.
    kept = [ln for ln in prev.split("\n")
            if _CARD_OVER_CAP_MARKER not in ln]
    frozen = "\n".join(kept).rstrip("\n") + (
        "\n- WARNING (%s): %s (%d bytes > %d hard cap); the card above is "
        "frozen at its last good content — cut prose in the ledger sources "
        "(kb/) and run `vellum state rebuild`.\n"
        % (when, _CARD_OVER_CAP_MARKER,
           len(card.encode("utf-8")), STATE_CARD_MAX_BYTES))
    return frozen, when


def _rebuild_unlocked(root, tracking, card):
    """Write the derived files + hashes WITHOUT taking the lock — for callers
    that already hold it (bible reindex must not self-deadlock).

    Card-cap overflow does not abort the rebuild: _tracking-state.json is
    still refreshed and the card is written frozen with a dated warning
    (state check, session-start, and the rebuild output surface the flag)."""
    card_out, over_since = _card_with_cap(root, card)
    tracking["card_over_cap"] = over_since
    atomic_write(util.project_file(root, *TRACKING_FILE.split("/")),
                 json.dumps(tracking, indent=2, ensure_ascii=False) + "\n")
    atomic_write(util.project_file(root, *CARD_FILE.split("/")), card_out)
    util.write_derived_hashes(root)


# ---------------------------------------------------------------------------
# check
# ---------------------------------------------------------------------------

def check(root, target=None):
    tp = util.project_file(root, *TRACKING_FILE.split("/"))
    cp = util.project_file(root, *CARD_FILE.split("/"))
    if not os.path.exists(tp) or not os.path.exists(cp):
        die("state files missing - run 'python scripts/vellum state rebuild' "
            "before starting a chapter.")
    try:
        with open(tp, "r", encoding="utf-8-sig") as f:
            tracking = json.load(f)
    except Exception:
        die("state/_tracking-state.json is unparseable - run 'python scripts/"
            "vellum state rebuild' to regenerate it.")
    if tracking.get("schema_version") != SCHEMA_VERSION:
        die("state schema is outdated (schema_version %r) - run 'python "
            "scripts/vellum state rebuild'." % tracking.get("schema_version"))
    if tracking.get("card_over_cap"):
        # Advisory, not a gate failure: the card is frozen (hash-consistent),
        # but the resume artifact may lag the sources. Surface it loudly.
        sys.stderr.write(
            "vellum: state card rebuild refused since %s - the card on disk "
            "is over the %d-byte cap and frozen; it may not reflect current "
            "kb/ content. Cut prose in the ledger sources and run 'vellum "
            "state rebuild'.\n"
            % (tracking["card_over_cap"], STATE_CARD_MAX_BYTES))

    chapters = util.list_chapters(root)

    # Resolve the write target: edits to an existing chapter are that
    # chapter's own transaction (revision, or the accepted->final close-out),
    # not a new-chapter start — the transactional invariants below are scoped
    # to new-chapter starts (spec 5.2).
    target_num, target_ch = None, None
    if target:
        m = re.match(r"^chapter-0*(\d+)\.md$",
                     os.path.basename(str(target).replace("\\", "/")))
        if m:
            target_num = int(m.group(1))
            for c in chapters:
                if c["num"] == target_num:
                    target_ch = c
                    break

    # Gate 2 acceptance precondition (spec 10.1): a pivotal chapter sitting at
    # status: accepted must carry its blind-reader artifact (verdict != LOST)
    # before its transaction can close — and before the next chapter starts.
    from .export import _blind_verdict, _blind_transcript_problems
    outlines = util.outline_files(root)
    for c in chapters:
        if c["fm"].get("status") != "accepted":
            continue
        o = outlines.get(c["num"])
        if not o or o["fm"].get("pivotal") is not True:
            continue
        verdict = _blind_verdict(root, c["num"])
        if verdict is None:
            die("chapter %s is pivotal but has no blind-reader artifact - "
                "acceptance requires work/critique-reports/blind-chapter-%02d"
                ".md with verdict ENGAGED or STALLED (never LOST); spawn "
                "@blind-reader and transcribe the verdict before closing the "
                "chapter." % (c["file"], c["num"]))
        if verdict == "LOST":
            die("chapter %s is pivotal and its blind verdict is LOST - "
                "acceptance is blocked (work/critique-reports/"
                "blind-chapter-%02d.md); revise the chapter and re-run the "
                "blind read." % (c["file"], c["num"]))
        # Same provenance binding as the readiness report: the artifact must
        # cite the blind-reader subagent transcript that carries the verdict.
        problems = _blind_transcript_problems(root, c["num"])
        if problems:
            die("chapter %s blind artifact provenance: %s" % (c["file"],
                                                              problems[0]))

    # pending capture: consult the tracking file first, then re-derive from
    # sources (a hand-edit that only flipped the flag must not pass). The
    # write that closes the pending chapter's own transaction (status: final)
    # is part of that transaction, not a new-chapter start.
    pending = [c for c in chapters if c["fm"].get("status") == "accepted"]
    if (pending and target_ch is not None
            and all(c["num"] == target_num for c in pending)):
        pass  # the target write is the pending chapter's own close-out
    elif tracking.get("pending_capture") or pending:
        die("pending_capture is true - the accepted chapter's transaction is "
            "not closed (kb capture + demolition decision + status: final). "
            "Complete the close-out before starting a new chapter.")

    mism = util.hash_mismatches(root)
    if mism:
        die("state:hand-edited - %s modified outside the engine; state files "
            "are engine-written. Run 'python scripts/vellum state rebuild' "
            "to repair." % ", ".join(mism))

    # Opt-in voice-debt gate (spec 3.8 / 5.2): when voice_debt_gate is true,
    # the post-write net's open tier-1 debt blocks the loop instead of
    # accruing silently.
    cfg = util.load_config(root)
    if cfg.get("voice_debt_gate") is True:
        debt = _voice_debt(root)
        if debt:
            die("voice debt gate (kb/project-config.json voice_debt_gate: "
                "true) - %d open tier-1 item(s) in work/voice-debt.json; "
                "resolve or explicitly clear them ('vellum debt list' / "
                "'vellum debt clear <id|all>') before continuing the "
                "chapter loop." % debt)

    # No half-committed chapter: when an approved outline exists for a higher
    # chapter than the newest on disk, the newest chapter must be closed.
    # Fires on new-chapter starts only - an edit to an existing chapter file
    # is a revision, never a start (the guards pass the write target).
    approved = sorted(n for n, o in outlines.items()
                      if o["fm"].get("approved") is True)
    if target_ch is None and approved and chapters:
        newest = max(approved)
        highest = chapters[-1]
        if newest > highest["num"]:
            st = highest["fm"].get("status")
            if st not in ("accepted", "final"):
                die("chapter %s is half-committed (status: %s) - close it out "
                    "(accept, capture, final) before starting chapter %s."
                    % (highest["file"], st, newest))

    sys.stdout.write("state ok.\n")
    return EXIT_OK
